### ISSUE TITLE
4.6.1 not reading iTunes date tag. Works in 4.6.

### ISSUE THREAD

**Issue by johanruda** [filebot/data#1]
Hey!

When I buy iTunes music and use FileBot to move it to where I want it, it won't read the date tag at all.
If I go back to 4.6 it works as it should. 

E:/OneDrive/Music/{albumartist}/{y} - {album}/{pi} -  {t} 
results in:

4.6:    E:\OneDrive\Music\Lissie\2016 - My Wild West\1 - My Wild West Overture
4.6.1: E:\OneDrive\Music\Lissie\ - My Wild West\1 - My Wild West Overture

**Comment by rednoah** [comment]
Are you using `AcoustID` or `ID3 Tags`? If you're using `ID3 Tags` please send me a screenshot of the [mediainfo table](http://i.imgur.com/VcxDVSO.png).

EDIT:

Nevermind. Fixed with **r3662**.
